version: "3.8"

services:
  web:
    build: .
    command: npm run start
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: "db"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    networks:
      - backend

  db:
    image: postgres
    environment:
      - POSTGRES_DB=vinyls
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5430:5432"
    networks:
      - backend


networks:
  backend:
    driver: bridge
    

